services:
  web:
    build: .
    expose:
      - "80"
    env_file:
      - .env
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.forge.rule=Host(`forge.hackclub.com`)"
      - "traefik.http.routers.forge.entrypoints=http,https"
      - "traefik.http.routers.forge.tls.certresolver=letsencrypt"
      - "traefik.http.services.forge.loadbalancer.server.port=80"
    volumes:
      - forge_storage:/rails/storage

volumes:
  forge_storage:
