# PostgreSQL configuration
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: forge_development

test:
  <<: *default
  database: forge_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cache_migrate
